INSERT INTO countries (country) VALUES ("Republica dominicana");
INSERT INTO countries (country) VALUES ("Honduras");
INSERT INTO countries (country) VALUES ("Costa rica");
INSERT INTO countries (country) VALUES ("Spain");
INSERT INTO countries (country) VALUES ("United states");
INSERT INTO countries (country) VALUES ("Mexico");
INSERT INTO countries (country) VALUES ("Venezuela");
INSERT INTO countries (country) VALUES ("Puerto rico");
INSERT INTO countries (country) VALUES ("El salvador");
INSERT INTO countries (country) VALUES ("Ecuador");
INSERT INTO countries (country) VALUES ("Colombia");
INSERT INTO countries (country) VALUES ("Argentina");
INSERT INTO countries (country) VALUES ("Uruguay");
INSERT INTO countries (country) VALUES ("Paraguay");
INSERT INTO countries (country) VALUES ("Brazil");
INSERT INTO countries (country) VALUES ("Panama");
INSERT INTO countries (country) VALUES ("Cuba");
INSERT INTO countries (country) VALUES ("Egipto");
INSERT INTO countries (country) VALUES ("China");
INSERT INTO countries (country) VALUES ("Italy");
INSERT INTO countries (country) VALUES ("Francia");
INSERT INTO countries (country) VALUES ("Rusia");
INSERT INTO countries (country) VALUES ("Portugal");
INSERT INTO countries (country) VALUES ("Suiza");
INSERT INTO countries (country) VALUES ("Reino unido");